OLLAMA_SERVICE_URL = "https://aaa-bbb-ccc-ddd.ngrok-free.app"

NGROK_BASIC_AUTH_USERNAME = "your-username"
NGROK_BASIC_AUTH_PASSWORD = "your-password"

PINECONE_API_KEY = "pcsk_xxxxx_xxxxxxxxxxxx"
PINECONE_INDEX_NAME = "agnos-task1-forum-firecrawl"
PINECONE_ENVIRONMENT_CLOUD = "aws"
PINECONE_ENVIRONMENT_REGION = "us-east-1"

FIRECRAWL_API_KEY = "fc-xxxxxxxxxxxxxxxxxx"